### PR TITLE
fixes #73 - Fix schemas

### LINKED ISSUE #73: "schema" property isn't respected
Several problems were found regarding the usage of "schema" PDB property:
- it is almost completely ignored (it seems only Oracle engine really sets current schema, other engines only used schema to get metadata and/or translate functions)
- the methods to get metadata (_getMetadata_, _getEntities_) return results that don't match the current schema -  for example, if schema is _not_ set in PDB properties, _updateEntity_ will do the following
    - check if the entity exists (since "schema" was not set in properties, it will try to find the entity in all the schemas)
    - if it doesn't exist, add it; at this point, if the entity exists on another schema, it won't be added to the current schema - inserting a new entry will either fail (if the engine doesn't look in other schemas if the entity is missing in the current one), or it will use the other schema (which translates into writing to a table that's not the one in the current default schema)
    - considering a migration scenario, where some data from a table is to be copied to other table with the same name, in the same database, but different schema: with a schema policy drop-create, _updateEntity_ might even try to _**drop the entity on the wrong schema**_

### PR DESCRIPTION
**Pull request by jmf-tls**
This addresses PULSEDEV-23140, where Oracle engine had some problems when schema property was defined and was different from the user, and all other engines weren't respecting the schema property at all.

The tests were updated accordingly.

### CODE REVIEW

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/H2Translator.java [hunk 1]
```diff
@@ -86,11 +86,7 @@ public String translate(Function f) {
         }
 
         // if it is a user-defined function
-        if (f.isUDF() && properties.isSchemaSet()) {
-            return properties.getSchema() + "." + function + "(" + expTranslated + ")";
-        } else {
-            return function + "(" + expTranslated + ")";
-        }
+        return function + "(" + expTranslated + ")";
```
Comment (dspereira004) [inline src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/H2Translator.java]: This means that the getSchema was never needed? Also, if you're gonna let this as-is, then the comment doesn't make sense anymore. The same thing applies to the other DB implementations.

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/MySqlEngine.java [hunk 2]
```diff
@@ -764,6 +768,63 @@ protected boolean checkConnection(final Connection conn) {
         }
     }
 
+    @Override
+    protected String getSchema() throws DatabaseEngineException {
+        try {
+            return this.conn.getCatalog();
```
Comment (dspereira004) [inline src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/MySqlEngine.java]: Why **getCatalog** instead of **getSchema** (the default method call on the superclasse)?

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java [hunk 3]
```diff
@@ -954,31 +944,21 @@ protected boolean checkConnection(final Connection conn) {
...
     }
 
-    /**
-     * Gets the schema. This implementation uses the username when the schema is null.
-     *
-     * @return The schema or the username when the first is null.
-     */
-    @Override
-    protected String getSchema() {
-        return Optional.ofNullable(super.getSchema()).orElse(properties.getUsername());
```
Comment (dspereira004) [inline src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java]: What happens now if we call getSchema and it is null?

File: src/test/java/com/feedzai/commons/sql/abstraction/engine/impl/abs/AbstractEngineSchemaTest.java [hunk 4]
```diff
@@ -639,9 +741,65 @@ protected EntityEntry createSpecialValueEntry(final Object columnValue) {
...
+     * @throws DatabaseEngineException  If anything goes wrong creating the schema.
+     * @throws DatabaseFactoryException If anything goes wrong connecting to the database.
+     * @since 2.1.13
+     */
+    public void dropCreateTestSchema() throws DatabaseEngineException, DatabaseFactoryException {
+        try (final DatabaseEngine engine = DatabaseFactory.getConnection(properties)) {
+            try {
+                dropSchema(engine, getTestSchema());
+            } catch (DatabaseEngineException e) {
+                // do nothing
```
Comment (dspereira004) [inline src/test/java/com/feedzai/commons/sql/abstraction/engine/impl/abs/AbstractEngineSchemaTest.java]: Why not just remove the try-catch here and let the Exception being thrown upwards to the other methods?

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/DB2Engine.java [hunk 5]
```diff
@@ -852,7 +852,45 @@ protected ResultIterator createResultIterator(Statement statement, String sql) t
...
+            // result needs to be trimmed because it has padding spaces
+            return schema == null ? null : schema.trim();
+        } catch (Exception e) {
+            throw new DatabaseEngineException("Could not get current schema", e);
+        }
+    }
+
+    @Override
+    protected void setSchema(final String schema) throws DatabaseEngineException {
+        final String findSchemaQuery = "SELECT count(*) FROM syscat.schemata WHERE SCHEMANAME = '" + schema + "'";
```
[the remark this answers is not in the document]
Comment (jmf-tls) [reply src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/DB2Engine.java]: Totally right, glad to have an extra pair of eyes looking at it!
Prepared statements don't even need values to be quotized, the driver will do the proper thing for us :+1:

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/DB2Engine.java [hunk 6]
```diff
@@ -862,8 +900,11 @@ protected ResultIterator createResultIterator(Statement statement, String sql) t
 
             s = conn.createStatement();
             rsColumns = s.executeQuery(
-                String.format("SELECT NAME, COLTYPE,SCALE  FROM sysibm.SYSCOLUMNS WHERE tbname='%s' and TBCREATOR=UPPER('%s')",
-                    name, Optional.ofNullable(properties.getSchema()).orElse(properties.getUsername()))
+                String.format(
+                    "SELECT NAME, COLTYPE, SCALE FROM sysibm.SYSCOLUMNS WHERE tbname LIKE '%s' and TBCREATOR LIKE '%s'",
```
[the remark this answers is not in the document]
Comment (jmf-tls) [reply src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/DB2Engine.java]: The _getMetadata(final String name)_ method was calling
_java.sql.DatabaseMetaData.getColumns(String catalog, String schemaPattern, String tableNamePattern, String columnNamePattern)_
for most DB engines (DB2 was one of the exceptions).

Because of that, the "name" in reality was a table name pattern which might include wildcards.
Since DB2 driver doesn't implement that _getColumns_ method, this one should behave is if it did, by accepting patterns instead of only exact names for schema and table; for this to work, it is necessary to use LIKE.

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/MySqlEngine.java (hunk 2 above)
Comment (jmf-tls) [reply src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/MySqlEngine.java]: For MySql schema and catalog are the same thing.
However, for some reason _getSchema()_ doesn't work, just returns _null_ :(

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java (hunk 3 above)
Comment (jmf-tls) [reply src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java]: With these changes, we have 3 sources for schema information:
* _properties.getSchema()_ from the PDB properties, which can be null (meaning "use the default schema")
* _AbstractDatabaseEngine.getSchema()_ which returns the current schema from the Connection -> the current schema name or null if there is none (there should always be a schema, which is why the _AbstractDatabaseEngine.connect()_ method will throw an exception if the connection schema is null)
* it is assumed that once set right after connecting to the DB, the current schema won't change; the _AbstractDatabaseEngine.currentSchema_ will contain the name of that schema, so that it can be used when needed without having to query the DB to get it

File: src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java [hunk 7]
```diff
@@ -241,27 +241,14 @@ protected void setParameterValues(final PreparedStatement ps, final int index, f
      * @since       2.1.4
      */
     private Object ensureNoUnderflow(Object val) {
-        if (val instanceof  Double) {
-            Double dblVal = (Double)val;
-            if (Math.abs(dblVal) <= 1.0e-131) {
-                val = ZERO;
+        if (val instanceof Double) {
```
Comment (dspereira004) [inline src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java]: Why not:

```java
if (val instanceof Double && Math.abs((Double) val) <= 1.0e-131) {
    return ZERO;
}

return val;
```

Comment (jmf-tls) [reply src/main/java/com/feedzai/commons/sql/abstraction/engine/impl/OracleEngine.java]: :)

**Comment by jmf-tls** [comment]
Since this is merged into master branch, I cleaned up history to have only 2 commits, both integrating all changes that were done following the review comments.
